
# Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
# Click nbfs://nbhost/SystemFileSystem/Templates/Other/properties.properties to edit this template


# ===========================
# CyberJogos - Supabase
# ===========================
spring.application.name=CyberJogos

# Conexao com Supabase (PostgreSQL)
spring.datasource.url=jdbc:postgresql://db.hepzgckldvwzfvhempcv.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=PlaycyberBD0?
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Sem servidor web (aplicacao desktop JFrame)
spring.main.web-application-type=none
spring.main.headless=false