
# Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
# Click nbfs://nbhost/SystemFileSystem/Templates/Other/properties.properties to edit this template


# ===========================
# CyberJogos - Configuracoes
# ===========================

spring.application.name=CyberJogos

# Banco H2 em memoria (para testar antes do Supabase)
spring.datasource.url=jdbc:h2:mem:cyberjogosdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Desativa o servidor web (so usamos JFrame)
spring.main.web-application-type=none